// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.20.0--rc1
// source: mhyc.proto

package mhyc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2SLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AreaId       int64  `protobuf:"varint,1,opt,name=AreaId,proto3" json:"AreaId,omitempty"`
	AccountId    int64  `protobuf:"varint,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	Token        string `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	UserId       int64  `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Fcm          int32  `protobuf:"varint,5,opt,name=Fcm,proto3" json:"Fcm,omitempty"`
	LoginPf      string `protobuf:"bytes,6,opt,name=LoginPf,proto3" json:"LoginPf,omitempty"`
	Timestamp    int64  `protobuf:"varint,7,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	CheckWordUrl string `protobuf:"bytes,8,opt,name=CheckWordUrl,proto3" json:"CheckWordUrl,omitempty"`
	CodeVersion  int32  `protobuf:"varint,9,opt,name=CodeVersion,proto3" json:"CodeVersion,omitempty"`
	ExcelVersion int32  `protobuf:"varint,10,opt,name=ExcelVersion,proto3" json:"ExcelVersion,omitempty"`
}

func (x *C2SLogin) Reset() {
	*x = C2SLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SLogin) ProtoMessage() {}

func (x *C2SLogin) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SLogin.ProtoReflect.Descriptor instead.
func (*C2SLogin) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{0}
}

func (x *C2SLogin) GetAreaId() int64 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

func (x *C2SLogin) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *C2SLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *C2SLogin) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *C2SLogin) GetFcm() int32 {
	if x != nil {
		return x.Fcm
	}
	return 0
}

func (x *C2SLogin) GetLoginPf() string {
	if x != nil {
		return x.LoginPf
	}
	return ""
}

func (x *C2SLogin) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *C2SLogin) GetCheckWordUrl() string {
	if x != nil {
		return x.CheckWordUrl
	}
	return ""
}

func (x *C2SLogin) GetCodeVersion() int32 {
	if x != nil {
		return x.CodeVersion
	}
	return 0
}

func (x *C2SLogin) GetExcelVersion() int32 {
	if x != nil {
		return x.ExcelVersion
	}
	return 0
}

type S2CLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag      int32 `protobuf:"varint,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	UserId   int32 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	NoCharge int32 `protobuf:"varint,3,opt,name=NoCharge,proto3" json:"NoCharge,omitempty"`
}

func (x *S2CLogin) Reset() {
	*x = S2CLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CLogin) ProtoMessage() {}

func (x *S2CLogin) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CLogin.ProtoReflect.Descriptor instead.
func (*S2CLogin) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{1}
}

func (x *S2CLogin) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *S2CLogin) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *S2CLogin) GetNoCharge() int32 {
	if x != nil {
		return x.NoCharge
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{2}
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{3}
}

type S2CRoleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32      `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	A      []*IntAttr `protobuf:"bytes,2,rep,name=A,proto3" json:"A,omitempty"`
	B      []*StrAttr `protobuf:"bytes,3,rep,name=B,proto3" json:"B,omitempty"`
}

func (x *S2CRoleInfo) Reset() {
	*x = S2CRoleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CRoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CRoleInfo) ProtoMessage() {}

func (x *S2CRoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CRoleInfo.ProtoReflect.Descriptor instead.
func (*S2CRoleInfo) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{4}
}

func (x *S2CRoleInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *S2CRoleInfo) GetA() []*IntAttr {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *S2CRoleInfo) GetB() []*StrAttr {
	if x != nil {
		return x.B
	}
	return nil
}

type IntAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	K int32 `protobuf:"varint,1,opt,name=k,proto3" json:"k,omitempty"`
	V int64 `protobuf:"varint,2,opt,name=v,proto3" json:"v,omitempty"`
}

func (x *IntAttr) Reset() {
	*x = IntAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntAttr) ProtoMessage() {}

func (x *IntAttr) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntAttr.ProtoReflect.Descriptor instead.
func (*IntAttr) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{5}
}

func (x *IntAttr) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *IntAttr) GetV() int64 {
	if x != nil {
		return x.V
	}
	return 0
}

type StrAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	K int32  `protobuf:"varint,1,opt,name=k,proto3" json:"k,omitempty"`
	V string `protobuf:"bytes,2,opt,name=v,proto3" json:"v,omitempty"`
}

func (x *StrAttr) Reset() {
	*x = StrAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrAttr) ProtoMessage() {}

func (x *StrAttr) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrAttr.ProtoReflect.Descriptor instead.
func (*StrAttr) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{6}
}

func (x *StrAttr) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *StrAttr) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

type S2CChangeMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag   int32 `protobuf:"varint,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	MapId int64 `protobuf:"varint,2,opt,name=MapId,proto3" json:"MapId,omitempty"`
	X     int32 `protobuf:"varint,3,opt,name=X,proto3" json:"X,omitempty"`
	Y     int32 `protobuf:"varint,4,opt,name=Y,proto3" json:"Y,omitempty"`
}

func (x *S2CChangeMap) Reset() {
	*x = S2CChangeMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CChangeMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CChangeMap) ProtoMessage() {}

func (x *S2CChangeMap) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CChangeMap.ProtoReflect.Descriptor instead.
func (*S2CChangeMap) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{7}
}

func (x *S2CChangeMap) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *S2CChangeMap) GetMapId() int64 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *S2CChangeMap) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *S2CChangeMap) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type C2SMailList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailType int32 `protobuf:"varint,1,opt,name=MailType,proto3" json:"MailType,omitempty"`
}

func (x *C2SMailList) Reset() {
	*x = C2SMailList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SMailList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SMailList) ProtoMessage() {}

func (x *C2SMailList) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SMailList.ProtoReflect.Descriptor instead.
func (*C2SMailList) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{8}
}

func (x *C2SMailList) GetMailType() int32 {
	if x != nil {
		return x.MailType
	}
	return 0
}

type S2CMailList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailList []*MailInfo `protobuf:"bytes,1,rep,name=MailList,proto3" json:"MailList,omitempty"`
}

func (x *S2CMailList) Reset() {
	*x = S2CMailList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CMailList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CMailList) ProtoMessage() {}

func (x *S2CMailList) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CMailList.ProtoReflect.Descriptor instead.
func (*S2CMailList) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{9}
}

func (x *S2CMailList) GetMailList() []*MailInfo {
	if x != nil {
		return x.MailList
	}
	return nil
}

type MailInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailId       int32       `protobuf:"varint,1,opt,name=MailId,proto3" json:"MailId,omitempty"`
	MailTplId    int32       `protobuf:"varint,2,opt,name=MailTplId,proto3" json:"MailTplId,omitempty"`
	MailTplParam string      `protobuf:"bytes,4,opt,name=MailTplParam,proto3" json:"MailTplParam,omitempty"`
	Title        string      `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`
	MailType     int32       `protobuf:"varint,6,opt,name=MailType,proto3" json:"MailType,omitempty"`
	IsRead       int32       `protobuf:"varint,7,opt,name=IsRead,proto3" json:"IsRead,omitempty"`
	IsReceive    int32       `protobuf:"varint,8,opt,name=IsReceive,proto3" json:"IsReceive,omitempty"`
	ReceiveTime  string      `protobuf:"bytes,9,opt,name=ReceiveTime,proto3" json:"ReceiveTime,omitempty"`
	Content      string      `protobuf:"bytes,10,opt,name=Content,proto3" json:"Content,omitempty"`
	AttachInfo   []*ItemInfo `protobuf:"bytes,11,rep,name=AttachInfo,proto3" json:"AttachInfo,omitempty"`
	AttachData   []*ItemData `protobuf:"bytes,12,rep,name=AttachData,proto3" json:"AttachData,omitempty"`
}

func (x *MailInfo) Reset() {
	*x = MailInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailInfo) ProtoMessage() {}

func (x *MailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailInfo.ProtoReflect.Descriptor instead.
func (*MailInfo) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{10}
}

func (x *MailInfo) GetMailId() int32 {
	if x != nil {
		return x.MailId
	}
	return 0
}

func (x *MailInfo) GetMailTplId() int32 {
	if x != nil {
		return x.MailTplId
	}
	return 0
}

func (x *MailInfo) GetMailTplParam() string {
	if x != nil {
		return x.MailTplParam
	}
	return ""
}

func (x *MailInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MailInfo) GetMailType() int32 {
	if x != nil {
		return x.MailType
	}
	return 0
}

func (x *MailInfo) GetIsRead() int32 {
	if x != nil {
		return x.IsRead
	}
	return 0
}

func (x *MailInfo) GetIsReceive() int32 {
	if x != nil {
		return x.IsReceive
	}
	return 0
}

func (x *MailInfo) GetReceiveTime() string {
	if x != nil {
		return x.ReceiveTime
	}
	return ""
}

func (x *MailInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MailInfo) GetAttachInfo() []*ItemInfo {
	if x != nil {
		return x.AttachInfo
	}
	return nil
}

func (x *MailInfo) GetAttachData() []*ItemData {
	if x != nil {
		return x.AttachData
	}
	return nil
}

type ItemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId    int32 `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	ItemNum   int64 `protobuf:"varint,2,opt,name=ItemNum,proto3" json:"ItemNum,omitempty"`
	Bind      int32 `protobuf:"varint,3,opt,name=Bind,proto3" json:"Bind,omitempty"`
	ItemValid int32 `protobuf:"varint,4,opt,name=ItemValid,proto3" json:"ItemValid,omitempty"`
	DSL       int32 `protobuf:"varint,5,opt,name=DSL,proto3" json:"DSL,omitempty"`
	DSS       int32 `protobuf:"varint,6,opt,name=DSS,proto3" json:"DSS,omitempty"`
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{11}
}

func (x *ItemInfo) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemInfo) GetItemNum() int64 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

func (x *ItemInfo) GetBind() int32 {
	if x != nil {
		return x.Bind
	}
	return 0
}

func (x *ItemInfo) GetItemValid() int32 {
	if x != nil {
		return x.ItemValid
	}
	return 0
}

func (x *ItemInfo) GetDSL() int32 {
	if x != nil {
		return x.DSL
	}
	return 0
}

func (x *ItemInfo) GetDSS() int32 {
	if x != nil {
		return x.DSS
	}
	return 0
}

type ItemData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string     `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Pos        int32      `protobuf:"varint,2,opt,name=Pos,proto3" json:"Pos,omitempty"`
	IId        int32      `protobuf:"varint,3,opt,name=IId,proto3" json:"IId,omitempty"`
	N          int64      `protobuf:"varint,4,opt,name=N,proto3" json:"N,omitempty"`
	B          int32      `protobuf:"varint,5,opt,name=B,proto3" json:"B,omitempty"`
	A          int32      `protobuf:"varint,6,opt,name=A,proto3" json:"A,omitempty"`
	V          int64      `protobuf:"varint,7,opt,name=V,proto3" json:"V,omitempty"`
	DSL        int32      `protobuf:"varint,8,opt,name=DSL,proto3" json:"DSL,omitempty"`
	DSS        int32      `protobuf:"varint,9,opt,name=DSS,proto3" json:"DSS,omitempty"`
	DSPos      int32      `protobuf:"varint,10,opt,name=DSPos,proto3" json:"DSPos,omitempty"`
	Attr       []*IntAttr `protobuf:"bytes,11,rep,name=Attr,proto3" json:"Attr,omitempty"`
	Pet2       *Pet2      `protobuf:"bytes,12,opt,name=Pet2,proto3" json:"Pet2,omitempty"`
	Star       int32      `protobuf:"varint,13,opt,name=Star,proto3" json:"Star,omitempty"`
	MaxStar    int32      `protobuf:"varint,14,opt,name=MaxStar,proto3" json:"MaxStar,omitempty"`
	IsNew      int32      `protobuf:"varint,15,opt,name=IsNew,proto3" json:"IsNew,omitempty"`
	State      int32      `protobuf:"varint,16,opt,name=State,proto3" json:"State,omitempty"`
	PartnerId  int64      `protobuf:"varint,17,opt,name=PartnerId,proto3" json:"PartnerId,omitempty"`
	Vows       string     `protobuf:"bytes,18,opt,name=Vows,proto3" json:"Vows,omitempty"`
	Lev        int32      `protobuf:"varint,19,opt,name=Lev,proto3" json:"Lev,omitempty"`
	FeatureId  []int32    `protobuf:"varint,20,rep,packed,name=FeatureId,proto3" json:"FeatureId,omitempty"`
	HLSkill    []*Skill   `protobuf:"bytes,21,rep,name=HLSkill,proto3" json:"HLSkill,omitempty"`
	YQ         int32      `protobuf:"varint,22,opt,name=YQ,proto3" json:"YQ,omitempty"`
	ObjType    int32      `protobuf:"varint,23,opt,name=ObjType,proto3" json:"ObjType,omitempty"`
	EquipPart  int32      `protobuf:"varint,24,opt,name=EquipPart,proto3" json:"EquipPart,omitempty"`
	Quality    int32      `protobuf:"varint,25,opt,name=Quality,proto3" json:"Quality,omitempty"`
	HJLev      int32      `protobuf:"varint,26,opt,name=HJLev,proto3" json:"HJLev,omitempty"`
	Exp        int32      `protobuf:"varint,27,opt,name=Exp,proto3" json:"Exp,omitempty"`
	TotalExp   int32      `protobuf:"varint,28,opt,name=TotalExp,proto3" json:"TotalExp,omitempty"`
	PEEffectId int32      `protobuf:"varint,29,opt,name=PEEffectId,proto3" json:"PEEffectId,omitempty"`
	PESuitId   int32      `protobuf:"varint,30,opt,name=PESuitId,proto3" json:"PESuitId,omitempty"`
	PetId      string     `protobuf:"bytes,31,opt,name=PetId,proto3" json:"PetId,omitempty"`
	Lock       int32      `protobuf:"varint,32,opt,name=Lock,proto3" json:"Lock,omitempty"`
}

func (x *ItemData) Reset() {
	*x = ItemData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemData) ProtoMessage() {}

func (x *ItemData) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemData.ProtoReflect.Descriptor instead.
func (*ItemData) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{12}
}

func (x *ItemData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemData) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *ItemData) GetIId() int32 {
	if x != nil {
		return x.IId
	}
	return 0
}

func (x *ItemData) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *ItemData) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *ItemData) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *ItemData) GetV() int64 {
	if x != nil {
		return x.V
	}
	return 0
}

func (x *ItemData) GetDSL() int32 {
	if x != nil {
		return x.DSL
	}
	return 0
}

func (x *ItemData) GetDSS() int32 {
	if x != nil {
		return x.DSS
	}
	return 0
}

func (x *ItemData) GetDSPos() int32 {
	if x != nil {
		return x.DSPos
	}
	return 0
}

func (x *ItemData) GetAttr() []*IntAttr {
	if x != nil {
		return x.Attr
	}
	return nil
}

func (x *ItemData) GetPet2() *Pet2 {
	if x != nil {
		return x.Pet2
	}
	return nil
}

func (x *ItemData) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *ItemData) GetMaxStar() int32 {
	if x != nil {
		return x.MaxStar
	}
	return 0
}

func (x *ItemData) GetIsNew() int32 {
	if x != nil {
		return x.IsNew
	}
	return 0
}

func (x *ItemData) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *ItemData) GetPartnerId() int64 {
	if x != nil {
		return x.PartnerId
	}
	return 0
}

func (x *ItemData) GetVows() string {
	if x != nil {
		return x.Vows
	}
	return ""
}

func (x *ItemData) GetLev() int32 {
	if x != nil {
		return x.Lev
	}
	return 0
}

func (x *ItemData) GetFeatureId() []int32 {
	if x != nil {
		return x.FeatureId
	}
	return nil
}

func (x *ItemData) GetHLSkill() []*Skill {
	if x != nil {
		return x.HLSkill
	}
	return nil
}

func (x *ItemData) GetYQ() int32 {
	if x != nil {
		return x.YQ
	}
	return 0
}

func (x *ItemData) GetObjType() int32 {
	if x != nil {
		return x.ObjType
	}
	return 0
}

func (x *ItemData) GetEquipPart() int32 {
	if x != nil {
		return x.EquipPart
	}
	return 0
}

func (x *ItemData) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *ItemData) GetHJLev() int32 {
	if x != nil {
		return x.HJLev
	}
	return 0
}

func (x *ItemData) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *ItemData) GetTotalExp() int32 {
	if x != nil {
		return x.TotalExp
	}
	return 0
}

func (x *ItemData) GetPEEffectId() int32 {
	if x != nil {
		return x.PEEffectId
	}
	return 0
}

func (x *ItemData) GetPESuitId() int32 {
	if x != nil {
		return x.PESuitId
	}
	return 0
}

func (x *ItemData) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *ItemData) GetLock() int32 {
	if x != nil {
		return x.Lock
	}
	return 0
}

type Pet2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string      `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	IId         int32       `protobuf:"varint,2,opt,name=IId,proto3" json:"IId,omitempty"`
	L           int32       `protobuf:"varint,3,opt,name=L,proto3" json:"L,omitempty"`
	E           int32       `protobuf:"varint,4,opt,name=E,proto3" json:"E,omitempty"`
	R           int32       `protobuf:"varint,5,opt,name=R,proto3" json:"R,omitempty"`
	ATalent     int32       `protobuf:"varint,6,opt,name=ATalent,proto3" json:"ATalent,omitempty"`
	DTalent     int32       `protobuf:"varint,7,opt,name=DTalent,proto3" json:"DTalent,omitempty"`
	HTalent     int32       `protobuf:"varint,8,opt,name=HTalent,proto3" json:"HTalent,omitempty"`
	Grow        int32       `protobuf:"varint,9,opt,name=Grow,proto3" json:"Grow,omitempty"`
	S           []*PetSkill `protobuf:"bytes,10,rep,name=S,proto3" json:"S,omitempty"`
	B           int32       `protobuf:"varint,11,opt,name=B,proto3" json:"B,omitempty"`
	N           string      `protobuf:"bytes,12,opt,name=N,proto3" json:"N,omitempty"`
	A           int32       `protobuf:"varint,15,opt,name=A,proto3" json:"A,omitempty"`
	D           int32       `protobuf:"varint,16,opt,name=D,proto3" json:"D,omitempty"`
	H           int32       `protobuf:"varint,17,opt,name=H,proto3" json:"H,omitempty"`
	IsNew       int32       `protobuf:"varint,18,opt,name=IsNew,proto3" json:"IsNew,omitempty"`
	TimeStamp   int64       `protobuf:"varint,19,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	MaxATalent  int32       `protobuf:"varint,20,opt,name=MaxATalent,proto3" json:"MaxATalent,omitempty"`
	MaxDTalent  int32       `protobuf:"varint,21,opt,name=MaxDTalent,proto3" json:"MaxDTalent,omitempty"`
	MaxHTalent  int32       `protobuf:"varint,22,opt,name=MaxHTalent,proto3" json:"MaxHTalent,omitempty"`
	MaxGrow     int32       `protobuf:"varint,23,opt,name=MaxGrow,proto3" json:"MaxGrow,omitempty"`
	Boundary    int32       `protobuf:"varint,24,opt,name=Boundary,proto3" json:"Boundary,omitempty"`
	Lock        int32       `protobuf:"varint,25,opt,name=Lock,proto3" json:"Lock,omitempty"`
	PetType     int32       `protobuf:"varint,27,opt,name=PetType,proto3" json:"PetType,omitempty"`
	Q           int32       `protobuf:"varint,28,opt,name=Q,proto3" json:"Q,omitempty"`
	Fv          int64       `protobuf:"varint,29,opt,name=Fv,proto3" json:"Fv,omitempty"`
	RaiseUpItem []*ItemInfo `protobuf:"bytes,30,rep,name=RaiseUpItem,proto3" json:"RaiseUpItem,omitempty"`
	Awaken      int32       `protobuf:"varint,31,opt,name=Awaken,proto3" json:"Awaken,omitempty"`
	BaseFv      int64       `protobuf:"varint,32,opt,name=BaseFv,proto3" json:"BaseFv,omitempty"`
	Equips      []string    `protobuf:"bytes,33,rep,name=Equips,proto3" json:"Equips,omitempty"`
	BdjjIds     []int32     `protobuf:"varint,34,rep,packed,name=BdjjIds,proto3" json:"BdjjIds,omitempty"`
	EA          int32       `protobuf:"varint,35,opt,name=EA,proto3" json:"EA,omitempty"`
	ED          int32       `protobuf:"varint,36,opt,name=ED,proto3" json:"ED,omitempty"`
	EH          int32       `protobuf:"varint,37,opt,name=EH,proto3" json:"EH,omitempty"`
}

func (x *Pet2) Reset() {
	*x = Pet2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pet2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pet2) ProtoMessage() {}

func (x *Pet2) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pet2.ProtoReflect.Descriptor instead.
func (*Pet2) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{13}
}

func (x *Pet2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pet2) GetIId() int32 {
	if x != nil {
		return x.IId
	}
	return 0
}

func (x *Pet2) GetL() int32 {
	if x != nil {
		return x.L
	}
	return 0
}

func (x *Pet2) GetE() int32 {
	if x != nil {
		return x.E
	}
	return 0
}

func (x *Pet2) GetR() int32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *Pet2) GetATalent() int32 {
	if x != nil {
		return x.ATalent
	}
	return 0
}

func (x *Pet2) GetDTalent() int32 {
	if x != nil {
		return x.DTalent
	}
	return 0
}

func (x *Pet2) GetHTalent() int32 {
	if x != nil {
		return x.HTalent
	}
	return 0
}

func (x *Pet2) GetGrow() int32 {
	if x != nil {
		return x.Grow
	}
	return 0
}

func (x *Pet2) GetS() []*PetSkill {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *Pet2) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *Pet2) GetN() string {
	if x != nil {
		return x.N
	}
	return ""
}

func (x *Pet2) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Pet2) GetD() int32 {
	if x != nil {
		return x.D
	}
	return 0
}

func (x *Pet2) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *Pet2) GetIsNew() int32 {
	if x != nil {
		return x.IsNew
	}
	return 0
}

func (x *Pet2) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *Pet2) GetMaxATalent() int32 {
	if x != nil {
		return x.MaxATalent
	}
	return 0
}

func (x *Pet2) GetMaxDTalent() int32 {
	if x != nil {
		return x.MaxDTalent
	}
	return 0
}

func (x *Pet2) GetMaxHTalent() int32 {
	if x != nil {
		return x.MaxHTalent
	}
	return 0
}

func (x *Pet2) GetMaxGrow() int32 {
	if x != nil {
		return x.MaxGrow
	}
	return 0
}

func (x *Pet2) GetBoundary() int32 {
	if x != nil {
		return x.Boundary
	}
	return 0
}

func (x *Pet2) GetLock() int32 {
	if x != nil {
		return x.Lock
	}
	return 0
}

func (x *Pet2) GetPetType() int32 {
	if x != nil {
		return x.PetType
	}
	return 0
}

func (x *Pet2) GetQ() int32 {
	if x != nil {
		return x.Q
	}
	return 0
}

func (x *Pet2) GetFv() int64 {
	if x != nil {
		return x.Fv
	}
	return 0
}

func (x *Pet2) GetRaiseUpItem() []*ItemInfo {
	if x != nil {
		return x.RaiseUpItem
	}
	return nil
}

func (x *Pet2) GetAwaken() int32 {
	if x != nil {
		return x.Awaken
	}
	return 0
}

func (x *Pet2) GetBaseFv() int64 {
	if x != nil {
		return x.BaseFv
	}
	return 0
}

func (x *Pet2) GetEquips() []string {
	if x != nil {
		return x.Equips
	}
	return nil
}

func (x *Pet2) GetBdjjIds() []int32 {
	if x != nil {
		return x.BdjjIds
	}
	return nil
}

func (x *Pet2) GetEA() int32 {
	if x != nil {
		return x.EA
	}
	return 0
}

func (x *Pet2) GetED() int32 {
	if x != nil {
		return x.ED
	}
	return 0
}

func (x *Pet2) GetEH() int32 {
	if x != nil {
		return x.EH
	}
	return 0
}

type Skill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I int32 `protobuf:"varint,1,opt,name=I,proto3" json:"I,omitempty"`
	L int32 `protobuf:"varint,2,opt,name=L,proto3" json:"L,omitempty"`
}

func (x *Skill) Reset() {
	*x = Skill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{14}
}

func (x *Skill) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *Skill) GetL() int32 {
	if x != nil {
		return x.L
	}
	return 0
}

type PetSkill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I    int32 `protobuf:"varint,1,opt,name=I,proto3" json:"I,omitempty"`
	L    int32 `protobuf:"varint,2,opt,name=L,proto3" json:"L,omitempty"`
	Lock int32 `protobuf:"varint,3,opt,name=Lock,proto3" json:"Lock,omitempty"`
}

func (x *PetSkill) Reset() {
	*x = PetSkill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PetSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetSkill) ProtoMessage() {}

func (x *PetSkill) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetSkill.ProtoReflect.Descriptor instead.
func (*PetSkill) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{15}
}

func (x *PetSkill) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *PetSkill) GetL() int32 {
	if x != nil {
		return x.L
	}
	return 0
}

func (x *PetSkill) GetLock() int32 {
	if x != nil {
		return x.Lock
	}
	return 0
}

type C2SGetMailAttach struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailId   int32 `protobuf:"varint,1,opt,name=MailId,proto3" json:"MailId,omitempty"`
	MailType int32 `protobuf:"varint,2,opt,name=MailType,proto3" json:"MailType,omitempty"`
}

func (x *C2SGetMailAttach) Reset() {
	*x = C2SGetMailAttach{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGetMailAttach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGetMailAttach) ProtoMessage() {}

func (x *C2SGetMailAttach) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGetMailAttach.ProtoReflect.Descriptor instead.
func (*C2SGetMailAttach) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{16}
}

func (x *C2SGetMailAttach) GetMailId() int32 {
	if x != nil {
		return x.MailId
	}
	return 0
}

func (x *C2SGetMailAttach) GetMailType() int32 {
	if x != nil {
		return x.MailType
	}
	return 0
}

type S2CGetMailAttach struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag int32 `protobuf:"varint,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
}

func (x *S2CGetMailAttach) Reset() {
	*x = S2CGetMailAttach{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGetMailAttach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGetMailAttach) ProtoMessage() {}

func (x *S2CGetMailAttach) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGetMailAttach.ProtoReflect.Descriptor instead.
func (*S2CGetMailAttach) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{17}
}

func (x *S2CGetMailAttach) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

type S2CNewMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2CNewMail) Reset() {
	*x = S2CNewMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CNewMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CNewMail) ProtoMessage() {}

func (x *S2CNewMail) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CNewMail.ProtoReflect.Descriptor instead.
func (*S2CNewMail) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{18}
}

type C2SActGiftNewReceive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid int32 `protobuf:"varint,1,opt,name=Gid,proto3" json:"Gid,omitempty"`
	Aid int32 `protobuf:"varint,2,opt,name=Aid,proto3" json:"Aid,omitempty"`
}

func (x *C2SActGiftNewReceive) Reset() {
	*x = C2SActGiftNewReceive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SActGiftNewReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SActGiftNewReceive) ProtoMessage() {}

func (x *C2SActGiftNewReceive) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SActGiftNewReceive.ProtoReflect.Descriptor instead.
func (*C2SActGiftNewReceive) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{19}
}

func (x *C2SActGiftNewReceive) GetGid() int32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *C2SActGiftNewReceive) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

type S2CActGiftNewReceive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag int32 `protobuf:"varint,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Gid int32 `protobuf:"varint,2,opt,name=Gid,proto3" json:"Gid,omitempty"`
	Aid int32 `protobuf:"varint,3,opt,name=Aid,proto3" json:"Aid,omitempty"`
}

func (x *S2CActGiftNewReceive) Reset() {
	*x = S2CActGiftNewReceive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CActGiftNewReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CActGiftNewReceive) ProtoMessage() {}

func (x *S2CActGiftNewReceive) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CActGiftNewReceive.ProtoReflect.Descriptor instead.
func (*S2CActGiftNewReceive) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{20}
}

func (x *S2CActGiftNewReceive) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *S2CActGiftNewReceive) GetGid() int32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *S2CActGiftNewReceive) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

type C2SRespect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type int32 `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *C2SRespect) Reset() {
	*x = C2SRespect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SRespect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRespect) ProtoMessage() {}

func (x *C2SRespect) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRespect.ProtoReflect.Descriptor instead.
func (*C2SRespect) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{21}
}

func (x *C2SRespect) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type S2CRespect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag   int32       `protobuf:"varint,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Prize []*ItemInfo `protobuf:"bytes,2,rep,name=Prize,proto3" json:"Prize,omitempty"`
	Type  int32       `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *S2CRespect) Reset() {
	*x = S2CRespect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CRespect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CRespect) ProtoMessage() {}

func (x *S2CRespect) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CRespect.ProtoReflect.Descriptor instead.
func (*S2CRespect) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{22}
}

func (x *S2CRespect) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *S2CRespect) GetPrize() []*ItemInfo {
	if x != nil {
		return x.Prize
	}
	return nil
}

func (x *S2CRespect) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type S2CServerTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	T int64 `protobuf:"varint,1,opt,name=T,proto3" json:"T,omitempty"`
}

func (x *S2CServerTime) Reset() {
	*x = S2CServerTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CServerTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CServerTime) ProtoMessage() {}

func (x *S2CServerTime) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CServerTime.ProtoReflect.Descriptor instead.
func (*S2CServerTime) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{23}
}

func (x *S2CServerTime) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

type S2CNewChatMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chatmessage *ChatMsg `protobuf:"bytes,1,opt,name=Chatmessage,proto3" json:"Chatmessage,omitempty"`
}

func (x *S2CNewChatMsg) Reset() {
	*x = S2CNewChatMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CNewChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CNewChatMsg) ProtoMessage() {}

func (x *S2CNewChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CNewChatMsg.ProtoReflect.Descriptor instead.
func (*S2CNewChatMsg) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{24}
}

func (x *S2CNewChatMsg) GetChatmessage() *ChatMsg {
	if x != nil {
		return x.Chatmessage
	}
	return nil
}

type ChatMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID               int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ChannelId        int32  `protobuf:"varint,2,opt,name=ChannelId,proto3" json:"ChannelId,omitempty"`
	Type             int32  `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Content          string `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	SenderId         int32  `protobuf:"varint,5,opt,name=SenderId,proto3" json:"SenderId,omitempty"`
	SenderNick       string `protobuf:"bytes,6,opt,name=SenderNick,proto3" json:"SenderNick,omitempty"`
	SenderRoleId     int32  `protobuf:"varint,7,opt,name=SenderRoleId,proto3" json:"SenderRoleId,omitempty"`
	SenderGodLevel   int64  `protobuf:"varint,8,opt,name=SenderGodLevel,proto3" json:"SenderGodLevel,omitempty"`
	AreaId           int64  `protobuf:"varint,9,opt,name=AreaId,proto3" json:"AreaId,omitempty"`
	SenderHead       int32  `protobuf:"varint,10,opt,name=SenderHead,proto3" json:"SenderHead,omitempty"`
	SenderHeadFrame  int32  `protobuf:"varint,11,opt,name=SenderHeadFrame,proto3" json:"SenderHeadFrame,omitempty"`
	SenderChatFrame  int32  `protobuf:"varint,12,opt,name=SenderChatFrame,proto3" json:"SenderChatFrame,omitempty"`
	SenderTitle      int32  `protobuf:"varint,13,opt,name=SenderTitle,proto3" json:"SenderTitle,omitempty"`
	SenderVIP        int32  `protobuf:"varint,14,opt,name=SenderVIP,proto3" json:"SenderVIP,omitempty"`
	AtUserShowAreaId int32  `protobuf:"varint,15,opt,name=AtUserShowAreaId,proto3" json:"AtUserShowAreaId,omitempty"`
	AtUserNick       string `protobuf:"bytes,16,opt,name=AtUserNick,proto3" json:"AtUserNick,omitempty"`
	AtUserId         int64  `protobuf:"varint,17,opt,name=AtUserId,proto3" json:"AtUserId,omitempty"`
	World            string `protobuf:"bytes,18,opt,name=World,proto3" json:"World,omitempty"`
	AtWorld          string `protobuf:"bytes,19,opt,name=AtWorld,proto3" json:"AtWorld,omitempty"`
	HideVIP          int32  `protobuf:"varint,20,opt,name=HideVIP,proto3" json:"HideVIP,omitempty"`
}

func (x *ChatMsg) Reset() {
	*x = ChatMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mhyc_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg) ProtoMessage() {}

func (x *ChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_mhyc_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return file_mhyc_proto_rawDescGZIP(), []int{25}
}

func (x *ChatMsg) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ChatMsg) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ChatMsg) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ChatMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMsg) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatMsg) GetSenderNick() string {
	if x != nil {
		return x.SenderNick
	}
	return ""
}

func (x *ChatMsg) GetSenderRoleId() int32 {
	if x != nil {
		return x.SenderRoleId
	}
	return 0
}

func (x *ChatMsg) GetSenderGodLevel() int64 {
	if x != nil {
		return x.SenderGodLevel
	}
	return 0
}

func (x *ChatMsg) GetAreaId() int64 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

func (x *ChatMsg) GetSenderHead() int32 {
	if x != nil {
		return x.SenderHead
	}
	return 0
}

func (x *ChatMsg) GetSenderHeadFrame() int32 {
	if x != nil {
		return x.SenderHeadFrame
	}
	return 0
}

func (x *ChatMsg) GetSenderChatFrame() int32 {
	if x != nil {
		return x.SenderChatFrame
	}
	return 0
}

func (x *ChatMsg) GetSenderTitle() int32 {
	if x != nil {
		return x.SenderTitle
	}
	return 0
}

func (x *ChatMsg) GetSenderVIP() int32 {
	if x != nil {
		return x.SenderVIP
	}
	return 0
}

func (x *ChatMsg) GetAtUserShowAreaId() int32 {
	if x != nil {
		return x.AtUserShowAreaId
	}
	return 0
}

func (x *ChatMsg) GetAtUserNick() string {
	if x != nil {
		return x.AtUserNick
	}
	return ""
}

func (x *ChatMsg) GetAtUserId() int64 {
	if x != nil {
		return x.AtUserId
	}
	return 0
}

func (x *ChatMsg) GetWorld() string {
	if x != nil {
		return x.World
	}
	return ""
}

func (x *ChatMsg) GetAtWorld() string {
	if x != nil {
		return x.AtWorld
	}
	return ""
}

func (x *ChatMsg) GetHideVIP() int32 {
	if x != nil {
		return x.HideVIP
	}
	return 0
}

var File_mhyc_proto protoreflect.FileDescriptor

var file_mhyc_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x68, 0x79, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x68,
	0x79, 0x63, 0x22, 0xa2, 0x02, 0x0a, 0x08, 0x43, 0x32, 0x53, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x41, 0x72, 0x65, 0x61, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x41, 0x72, 0x65, 0x61, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x46, 0x63, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x46, 0x63, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x66,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x66, 0x12,
	0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x22, 0x0a,
	0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x57, 0x6f, 0x72, 0x64, 0x55, 0x72, 0x6c, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x57, 0x6f, 0x72, 0x64, 0x55, 0x72,
	0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x43, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x45, 0x78, 0x63, 0x65, 0x6c, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x45, 0x78, 0x63, 0x65, 0x6c,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x50, 0x0a, 0x08, 0x53, 0x32, 0x43, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x54, 0x61, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x4e, 0x6f, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x4e, 0x6f, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x22, 0x06, 0x0a, 0x04, 0x50, 0x69, 0x6e,
	0x67, 0x22, 0x06, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x22, 0x5f, 0x0a, 0x0b, 0x53, 0x32, 0x43,
	0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x01, 0x41, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x68,
	0x79, 0x63, 0x2e, 0x49, 0x6e, 0x74, 0x41, 0x74, 0x74, 0x72, 0x52, 0x01, 0x41, 0x12, 0x1b, 0x0a,
	0x01, 0x42, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x68, 0x79, 0x63, 0x2e,
	0x53, 0x74, 0x72, 0x41, 0x74, 0x74, 0x72, 0x52, 0x01, 0x42, 0x22, 0x25, 0x0a, 0x07, 0x49, 0x6e,
	0x74, 0x41, 0x74, 0x74, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x6b, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01,
	0x76, 0x22, 0x25, 0x0a, 0x07, 0x53, 0x74, 0x72, 0x41, 0x74, 0x74, 0x72, 0x12, 0x0c, 0x0a, 0x01,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x6b, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x76, 0x22, 0x52, 0x0a, 0x0c, 0x53, 0x32, 0x43, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x61, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x54, 0x61, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61,
	0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4d, 0x61, 0x70, 0x49, 0x64,
	0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x58, 0x12, 0x0c,
	0x0a, 0x01, 0x59, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x59, 0x22, 0x29, 0x0a, 0x0b,
	0x43, 0x32, 0x53, 0x4d, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x4d,
	0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4d,
	0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x22, 0x39, 0x0a, 0x0b, 0x53, 0x32, 0x43, 0x4d, 0x61,
	0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x08, 0x4d, 0x61, 0x69, 0x6c, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x68, 0x79, 0x63, 0x2e,
	0x4d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x4d, 0x61, 0x69, 0x6c, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0xe8, 0x02, 0x0a, 0x08, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x16, 0x0a, 0x06, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x69, 0x6c, 0x54,
	0x70, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x4d, 0x61, 0x69, 0x6c,
	0x54, 0x70, 0x6c, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x70, 0x6c,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x4d, 0x61, 0x69,
	0x6c, 0x54, 0x70, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x49,
	0x73, 0x52, 0x65, 0x61, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x49, 0x73, 0x52,
	0x65, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x49, 0x73, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a,
	0x0a, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x0b, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x68, 0x79, 0x63, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x0a, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2e, 0x0a,
	0x0a, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x18, 0x0c, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x68, 0x79, 0x63, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x0a, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x22, 0x92, 0x01,
	0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74,
	0x65, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04,
	0x42, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x42, 0x69, 0x6e, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x49, 0x74, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x49, 0x74, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x44, 0x53, 0x4c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x44, 0x53, 0x4c,
	0x12, 0x10, 0x0a, 0x03, 0x44, 0x53, 0x53, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x44,
	0x53, 0x53, 0x22, 0xe2, 0x05, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x50, 0x6f,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x49, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x4e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01,
	0x4e, 0x12, 0x0c, 0x0a, 0x01, 0x42, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x42, 0x12,
	0x0c, 0x0a, 0x01, 0x41, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x41, 0x12, 0x0c, 0x0a,
	0x01, 0x56, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x56, 0x12, 0x10, 0x0a, 0x03, 0x44,
	0x53, 0x4c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x44, 0x53, 0x4c, 0x12, 0x10, 0x0a,
	0x03, 0x44, 0x53, 0x53, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x44, 0x53, 0x53, 0x12,
	0x14, 0x0a, 0x05, 0x44, 0x53, 0x50, 0x6f, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x44, 0x53, 0x50, 0x6f, 0x73, 0x12, 0x21, 0x0a, 0x04, 0x41, 0x74, 0x74, 0x72, 0x18, 0x0b, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x68, 0x79, 0x63, 0x2e, 0x49, 0x6e, 0x74, 0x41, 0x74,
	0x74, 0x72, 0x52, 0x04, 0x41, 0x74, 0x74, 0x72, 0x12, 0x1e, 0x0a, 0x04, 0x50, 0x65, 0x74, 0x32,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x68, 0x79, 0x63, 0x2e, 0x50, 0x65,
	0x74, 0x32, 0x52, 0x04, 0x50, 0x65, 0x74, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x72,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x74, 0x61, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x61, 0x78, 0x53, 0x74, 0x61, 0x72, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d,
	0x61, 0x78, 0x53, 0x74, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x4e, 0x65, 0x77, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x49, 0x73, 0x4e, 0x65, 0x77, 0x12, 0x14, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x11, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x56, 0x6f, 0x77, 0x73, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x56, 0x6f, 0x77, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x65, 0x76, 0x18, 0x13, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x4c, 0x65, 0x76, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x49, 0x64, 0x18, 0x14, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x46, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x07, 0x48, 0x4c, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x18,
	0x15, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x68, 0x79, 0x63, 0x2e, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x52, 0x07, 0x48, 0x4c, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x59,
	0x51, 0x18, 0x16, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x59, 0x51, 0x12, 0x18, 0x0a, 0x07, 0x4f,
	0x62, 0x6a, 0x54, 0x79, 0x70, 0x65, 0x18, 0x17, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4f, 0x62,
	0x6a, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x71, 0x75, 0x69, 0x70, 0x50, 0x61,
	0x72, 0x74, 0x18, 0x18, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x45, 0x71, 0x75, 0x69, 0x70, 0x50,
	0x61, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x19,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x48, 0x4a, 0x4c, 0x65, 0x76, 0x18, 0x1a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x48, 0x4a,
	0x4c, 0x65, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x78, 0x70, 0x18, 0x1b, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x45, 0x78, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x78,
	0x70, 0x18, 0x1c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x78,
	0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x45, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18,
	0x1d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x50, 0x45, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x45, 0x53, 0x75, 0x69, 0x74, 0x49, 0x64, 0x18, 0x1e, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x50, 0x45, 0x53, 0x75, 0x69, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x50, 0x65, 0x74, 0x49, 0x64, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x65,
	0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x6f, 0x63, 0x6b, 0x18, 0x20, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x4c, 0x6f, 0x63, 0x6b, 0x22, 0xf2, 0x05, 0x0a, 0x04, 0x50, 0x65, 0x74, 0x32,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x49, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x49,
	0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x4c,
	0x12, 0x0c, 0x0a, 0x01, 0x45, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x45, 0x12, 0x0c,
	0x0a, 0x01, 0x52, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x52, 0x12, 0x18, 0x0a, 0x07,
	0x41, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x41,
	0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x54, 0x61, 0x6c, 0x65, 0x6e,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x44, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x48, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x48, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x72,
	0x6f, 0x77, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x47, 0x72, 0x6f, 0x77, 0x12, 0x1c,
	0x0a, 0x01, 0x53, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x68, 0x79, 0x63,
	0x2e, 0x50, 0x65, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x01, 0x53, 0x12, 0x0c, 0x0a, 0x01,
	0x42, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x42, 0x12, 0x0c, 0x0a, 0x01, 0x4e, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x4e, 0x12, 0x0c, 0x0a, 0x01, 0x41, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x41, 0x12, 0x0c, 0x0a, 0x01, 0x44, 0x18, 0x10, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x01, 0x44, 0x12, 0x0c, 0x0a, 0x01, 0x48, 0x18, 0x11, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x48, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x4e, 0x65, 0x77, 0x18, 0x12, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x49, 0x73, 0x4e, 0x65, 0x77, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x13, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x61, 0x78, 0x41, 0x54, 0x61,
	0x6c, 0x65, 0x6e, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x4d, 0x61, 0x78, 0x41,
	0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x61, 0x78, 0x44, 0x54, 0x61,
	0x6c, 0x65, 0x6e, 0x74, 0x18, 0x15, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x4d, 0x61, 0x78, 0x44,
	0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x61, 0x78, 0x48, 0x54, 0x61,
	0x6c, 0x65, 0x6e, 0x74, 0x18, 0x16, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x4d, 0x61, 0x78, 0x48,
	0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x78, 0x47, 0x72, 0x6f,
	0x77, 0x18, 0x17, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x61, 0x78, 0x47, 0x72, 0x6f, 0x77,
	0x12, 0x1a, 0x0a, 0x08, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x18, 0x18, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x4c, 0x6f, 0x63, 0x6b, 0x18, 0x19, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4c, 0x6f, 0x63, 0x6b,
	0x12, 0x18, 0x0a, 0x07, 0x50, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x1b, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x50, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x51, 0x18,
	0x1c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x51, 0x12, 0x0e, 0x0a, 0x02, 0x46, 0x76, 0x18, 0x1d,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x46, 0x76, 0x12, 0x30, 0x0a, 0x0b, 0x52, 0x61, 0x69, 0x73,
	0x65, 0x55, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x1e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x6d, 0x68, 0x79, 0x63, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x52,
	0x61, 0x69, 0x73, 0x65, 0x55, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x77,
	0x61, 0x6b, 0x65, 0x6e, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x41, 0x77, 0x61, 0x6b,
	0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x61, 0x73, 0x65, 0x46, 0x76, 0x18, 0x20, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x42, 0x61, 0x73, 0x65, 0x46, 0x76, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x71,
	0x75, 0x69, 0x70, 0x73, 0x18, 0x21, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x64, 0x6a, 0x6a, 0x49, 0x64, 0x73, 0x18, 0x22, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x07, 0x42, 0x64, 0x6a, 0x6a, 0x49, 0x64, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x45, 0x41, 0x18, 0x23, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x45, 0x41, 0x12, 0x0e, 0x0a, 0x02,
	0x45, 0x44, 0x18, 0x24, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x45, 0x44, 0x12, 0x0e, 0x0a, 0x02,
	0x45, 0x48, 0x18, 0x25, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x45, 0x48, 0x22, 0x23, 0x0a, 0x05,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x0c, 0x0a, 0x01, 0x49, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x49, 0x12, 0x0c, 0x0a, 0x01, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01,
	0x4c, 0x22, 0x3a, 0x0a, 0x08, 0x50, 0x65, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x0c, 0x0a,
	0x01, 0x49, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x49, 0x12, 0x0c, 0x0a, 0x01, 0x4c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x4c, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x6f, 0x63,
	0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4c, 0x6f, 0x63, 0x6b, 0x22, 0x46, 0x0a,
	0x10, 0x43, 0x32, 0x53, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x69, 0x6c, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x61, 0x69,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4d, 0x61, 0x69,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x22, 0x24, 0x0a, 0x10, 0x53, 0x32, 0x43, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x69, 0x6c, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x54, 0x61, 0x67, 0x22, 0x0c, 0x0a, 0x0a, 0x53,
	0x32, 0x43, 0x4e, 0x65, 0x77, 0x4d, 0x61, 0x69, 0x6c, 0x22, 0x3a, 0x0a, 0x14, 0x43, 0x32, 0x53,
	0x41, 0x63, 0x74, 0x47, 0x69, 0x66, 0x74, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x47, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x41, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x14, 0x53, 0x32, 0x43, 0x41, 0x63, 0x74, 0x47,
	0x69, 0x66, 0x74, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x54, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x54, 0x61, 0x67, 0x12,
	0x10, 0x0a, 0x03, 0x47, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x47, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x41, 0x69, 0x64, 0x22, 0x20, 0x0a, 0x0a, 0x43, 0x32, 0x53, 0x52, 0x65, 0x73, 0x70, 0x65, 0x63,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x58, 0x0a, 0x0a, 0x53, 0x32, 0x43, 0x52, 0x65, 0x73, 0x70,
	0x65, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x54, 0x61, 0x67, 0x12, 0x24, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x68, 0x79, 0x63, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x1d, 0x0a, 0x0d, 0x53, 0x32, 0x43, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x0c, 0x0a, 0x01, 0x54, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x54, 0x22, 0x40,
	0x0a, 0x0d, 0x53, 0x32, 0x43, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x12,
	0x2f, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x68, 0x79, 0x63, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x4d, 0x73, 0x67, 0x52, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0xeb, 0x04, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x69,
	0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x4e, 0x69, 0x63, 0x6b, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x47, 0x6f, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x47, 0x6f, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x41, 0x72, 0x65, 0x61, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x41, 0x72, 0x65, 0x61, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x48, 0x65, 0x61, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x48, 0x65, 0x61, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x48, 0x65, 0x61, 0x64, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x48, 0x65, 0x61, 0x64, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x53, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x56, 0x49, 0x50, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x56, 0x49, 0x50, 0x12, 0x2a, 0x0a, 0x10,
	0x41, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x77, 0x41, 0x72, 0x65, 0x61, 0x49, 0x64,
	0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x41, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68,
	0x6f, 0x77, 0x41, 0x72, 0x65, 0x61, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x4e, 0x69, 0x63, 0x6b, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x69, 0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x11, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x41, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x18, 0x12, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x74,
	0x57, 0x6f, 0x72, 0x6c, 0x64, 0x18, 0x13, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x74, 0x57,
	0x6f, 0x72, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x69, 0x64, 0x65, 0x56, 0x49, 0x50, 0x18,
	0x14, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x48, 0x69, 0x64, 0x65, 0x56, 0x49, 0x50, 0x42, 0x08,
	0x5a, 0x06, 0x2e, 0x2f, 0x6d, 0x68, 0x79, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mhyc_proto_rawDescOnce sync.Once
	file_mhyc_proto_rawDescData = file_mhyc_proto_rawDesc
)

func file_mhyc_proto_rawDescGZIP() []byte {
	file_mhyc_proto_rawDescOnce.Do(func() {
		file_mhyc_proto_rawDescData = protoimpl.X.CompressGZIP(file_mhyc_proto_rawDescData)
	})
	return file_mhyc_proto_rawDescData
}

var file_mhyc_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_mhyc_proto_goTypes = []interface{}{
	(*C2SLogin)(nil),             // 0: mhyc.C2SLogin
	(*S2CLogin)(nil),             // 1: mhyc.S2CLogin
	(*Ping)(nil),                 // 2: mhyc.Ping
	(*Pong)(nil),                 // 3: mhyc.Pong
	(*S2CRoleInfo)(nil),          // 4: mhyc.S2CRoleInfo
	(*IntAttr)(nil),              // 5: mhyc.IntAttr
	(*StrAttr)(nil),              // 6: mhyc.StrAttr
	(*S2CChangeMap)(nil),         // 7: mhyc.S2CChangeMap
	(*C2SMailList)(nil),          // 8: mhyc.C2SMailList
	(*S2CMailList)(nil),          // 9: mhyc.S2CMailList
	(*MailInfo)(nil),             // 10: mhyc.MailInfo
	(*ItemInfo)(nil),             // 11: mhyc.ItemInfo
	(*ItemData)(nil),             // 12: mhyc.ItemData
	(*Pet2)(nil),                 // 13: mhyc.Pet2
	(*Skill)(nil),                // 14: mhyc.Skill
	(*PetSkill)(nil),             // 15: mhyc.PetSkill
	(*C2SGetMailAttach)(nil),     // 16: mhyc.C2SGetMailAttach
	(*S2CGetMailAttach)(nil),     // 17: mhyc.S2CGetMailAttach
	(*S2CNewMail)(nil),           // 18: mhyc.S2CNewMail
	(*C2SActGiftNewReceive)(nil), // 19: mhyc.C2SActGiftNewReceive
	(*S2CActGiftNewReceive)(nil), // 20: mhyc.S2CActGiftNewReceive
	(*C2SRespect)(nil),           // 21: mhyc.C2SRespect
	(*S2CRespect)(nil),           // 22: mhyc.S2CRespect
	(*S2CServerTime)(nil),        // 23: mhyc.S2CServerTime
	(*S2CNewChatMsg)(nil),        // 24: mhyc.S2CNewChatMsg
	(*ChatMsg)(nil),              // 25: mhyc.ChatMsg
}
var file_mhyc_proto_depIdxs = []int32{
	5,  // 0: mhyc.S2CRoleInfo.A:type_name -> mhyc.IntAttr
	6,  // 1: mhyc.S2CRoleInfo.B:type_name -> mhyc.StrAttr
	10, // 2: mhyc.S2CMailList.MailList:type_name -> mhyc.MailInfo
	11, // 3: mhyc.MailInfo.AttachInfo:type_name -> mhyc.ItemInfo
	12, // 4: mhyc.MailInfo.AttachData:type_name -> mhyc.ItemData
	5,  // 5: mhyc.ItemData.Attr:type_name -> mhyc.IntAttr
	13, // 6: mhyc.ItemData.Pet2:type_name -> mhyc.Pet2
	14, // 7: mhyc.ItemData.HLSkill:type_name -> mhyc.Skill
	15, // 8: mhyc.Pet2.S:type_name -> mhyc.PetSkill
	11, // 9: mhyc.Pet2.RaiseUpItem:type_name -> mhyc.ItemInfo
	11, // 10: mhyc.S2CRespect.Prize:type_name -> mhyc.ItemInfo
	25, // 11: mhyc.S2CNewChatMsg.Chatmessage:type_name -> mhyc.ChatMsg
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_mhyc_proto_init() }
func file_mhyc_proto_init() {
	if File_mhyc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mhyc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CRoleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CChangeMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SMailList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CMailList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pet2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Skill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PetSkill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGetMailAttach); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGetMailAttach); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CNewMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SActGiftNewReceive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CActGiftNewReceive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SRespect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CRespect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CServerTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CNewChatMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mhyc_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mhyc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mhyc_proto_goTypes,
		DependencyIndexes: file_mhyc_proto_depIdxs,
		MessageInfos:      file_mhyc_proto_msgTypes,
	}.Build()
	File_mhyc_proto = out.File
	file_mhyc_proto_rawDesc = nil
	file_mhyc_proto_goTypes = nil
	file_mhyc_proto_depIdxs = nil
}
